#![allow(unused_comparisons)]

type MapperFn = fn(u16) -> Option<u16>;

pub struct Mapper {
  pub cpu: MapperFn,
  pub ppu: MapperFn,
}

const MXXX: Mapper = Mapper {
  cpu: |_| todo!(),
  ppu: |_| todo!(),
};

const M000: Mapper = Mapper {
  cpu: |addr| {
    if addr >= 0x8000 && addr <= 0xFFFF {}
    None
  },
  ppu: |addr| {
    if addr >= 0x8000 && addr <= 0xFFFF {}
    None
  },
};

pub const MAPPERS: [Mapper; 256] = [
  M000, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX,
  MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX,
  MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX,
  MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX,
  MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX,
  MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX,
  MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX,
  MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX,
  MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX,
  MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX,
  MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX,
  MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX,
  MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX,
  MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX,
  MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX,
  MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX, MXXX,
];
